GET http://localhost:4200/books
 
###
 
GET  http://localhost:4200/books/11
 
###
 
GET http://localhost:4200/books?title=test
 
 
###
POST http://localhost:4200/books
Content-Type: application/json
 
{
    "title": "Чистий код",
    "price": 1000,
    "is_active": true
}


###
GET http://localhost:4200/authors

###

GET http://localhost:4200/authors/1

###
PUT http://localhost:4200/books/12
Content-Type: application/json

{
  "title": "Нова книжка",
  "price": 300,
  "is_active": true,
  "authors_id": [1, 2]
}

###

DELETE  http://localhost:4200/books/12